# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: started
  #schedule:
  #  - cron: 0 8 * * 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install env
        run: |
          cat /etc/apt/sources.list
          sudo rm -rf /etc/apt/sources.list.d/*

      - name: Build with Maven
        run: java -version

        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          firefox -v
          geckodriver --version
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          ls
          pwd
